services:
  take-unique-turn:
    container_name: server-node
    build:
      dockerfile: src/Dockerfile
      context: .
    ports:
      - "2489:8000"
      - "4332:4321"
    tty: true
    volumes:
      - ./src:/src
      - node_modules:/src/node_modules
    env_file: local_env/.env
    stop_grace_period: 1s
    entrypoint: bash -c "yarn dev-server:start"
    networks:
      - shared

volumes:
  node_modules:

networks:
  shared:
    name: shared
    external:
      true
